# Generated by Django 4.2.16 on 2024-09-21 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_book_id_alter_category_id_alter_review_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='popular_book',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='top_selling',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='upcoming_book',
            field=models.BooleanField(default=False),
        ),
    ]
