# Generated by Django 4.2.16 on 2024-09-21 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_id_alter_orderitem_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='district',
        ),
        migrations.RemoveField(
            model_name='order',
            name='division',
        ),
    ]
