# Generated by Django 4.2.16 on 2024-09-21 11:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_order_district_remove_order_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='district',
            field=models.CharField(default=datetime.datetime(2024, 9, 21, 11, 27, 49, 567611, tzinfo=datetime.timezone.utc), max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='division',
            field=models.CharField(default=datetime.datetime(2024, 9, 21, 11, 27, 53, 641322, tzinfo=datetime.timezone.utc), max_length=20),
            preserve_default=False,
        ),
    ]
